version: "3"

services:
  frontend:
    image: nieine/inseri-frontend:2022-03-15 #2022-02-18
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=apps.inseri.swiss
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=apps.inseri.swiss

  backend:
    image: nieine/inseri-backend:2022-03-15 #2022-02-18
    expose:
      - "3000"
    env_file:
      - ./inseriPersistentDataVolume/backend/.settings/.env.prod
    environment:
      - VIRTUAL_HOST=node.inseri.swiss
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=node.inseri.swiss
    volumes:
      - ./inseriPersistentDataVolume/backend/files:/usr/src/app/files
    restart: unless-stopped

  mongo_inseri:
    image: mongo:5.0
    volumes:
      - ./inseriPersistentDataVolume/mongoData_inseri:/data/db
    restart: always

networks:
  default:
    external: true
    name: inseri-net
